
- name: Install Icinga classic CGIs
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ icingaclassic_packages_yum }}'

- include: setup-cgi-uwsgi.yml
  when: icingaclassic_with_uwsgi

- meta: flush_handlers

- name: Provide CGI config
  template:
    src: cgi.cfg.j2
    dest: '{{ icingaclassic_cgi_config }}'
    group: '{{ icingaclassic_cgi_group }}'
    backup: '{{ icingaclassic_backup_configs }}'

- name: Start icinga classic
  service:
    name: '{{ icingaclassic_cgi_service }}'
    state: started
    enabled: true
